/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Genre, // @ts-ignore
  Movie, // @ts-ignore
  Series, // @ts-ignore
  VideoContent,
} from "@prisma/client";

export class GenreServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.GenreCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreCountArgs>
  ): Promise<number> {
    return this.prisma.genre.count(args);
  }

  async genres<T extends Prisma.GenreFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreFindManyArgs>
  ): Promise<Genre[]> {
    return this.prisma.genre.findMany(args);
  }
  async genre<T extends Prisma.GenreFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreFindUniqueArgs>
  ): Promise<Genre | null> {
    return this.prisma.genre.findUnique(args);
  }
  async createGenre<T extends Prisma.GenreCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreCreateArgs>
  ): Promise<Genre> {
    return this.prisma.genre.create<T>(args);
  }
  async updateGenre<T extends Prisma.GenreUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreUpdateArgs>
  ): Promise<Genre> {
    return this.prisma.genre.update<T>(args);
  }
  async deleteGenre<T extends Prisma.GenreDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.GenreDeleteArgs>
  ): Promise<Genre> {
    return this.prisma.genre.delete(args);
  }

  async getMovie(parentId: string): Promise<Movie | null> {
    return this.prisma.genre
      .findUnique({
        where: { id: parentId },
      })
      .movie();
  }

  async getSeries(parentId: string): Promise<Series | null> {
    return this.prisma.genre
      .findUnique({
        where: { id: parentId },
      })
      .series();
  }

  async getVideoContent(parentId: string): Promise<VideoContent | null> {
    return this.prisma.genre
      .findUnique({
        where: { id: parentId },
      })
      .videoContent();
  }
}
