/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Series } from "./Series";
import { SeriesCountArgs } from "./SeriesCountArgs";
import { SeriesFindManyArgs } from "./SeriesFindManyArgs";
import { SeriesFindUniqueArgs } from "./SeriesFindUniqueArgs";
import { CreateSeriesArgs } from "./CreateSeriesArgs";
import { UpdateSeriesArgs } from "./UpdateSeriesArgs";
import { DeleteSeriesArgs } from "./DeleteSeriesArgs";
import { GenreFindManyArgs } from "../../genre/base/GenreFindManyArgs";
import { Genre } from "../../genre/base/Genre";
import { User } from "../../user/base/User";
import { UserSeriesMapping } from "../../userSeriesMapping/base/UserSeriesMapping";
import { SeriesService } from "../series.service";
@graphql.Resolver(() => Series)
export class SeriesResolverBase {
  constructor(protected readonly service: SeriesService) {}

  async _seriesItemsMeta(
    @graphql.Args() args: SeriesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Series])
  async seriesItems(
    @graphql.Args() args: SeriesFindManyArgs
  ): Promise<Series[]> {
    return this.service.seriesItems(args);
  }

  @graphql.Query(() => Series, { nullable: true })
  async series(
    @graphql.Args() args: SeriesFindUniqueArgs
  ): Promise<Series | null> {
    const result = await this.service.series(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Series)
  async createSeries(@graphql.Args() args: CreateSeriesArgs): Promise<Series> {
    return await this.service.createSeries({
      ...args,
      data: {
        ...args.data,

        director: {
          connect: args.data.director,
        },

        userSeriesMapping: args.data.userSeriesMapping
          ? {
              connect: args.data.userSeriesMapping,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Series)
  async updateSeries(
    @graphql.Args() args: UpdateSeriesArgs
  ): Promise<Series | null> {
    try {
      return await this.service.updateSeries({
        ...args,
        data: {
          ...args.data,

          director: {
            connect: args.data.director,
          },

          userSeriesMapping: args.data.userSeriesMapping
            ? {
                connect: args.data.userSeriesMapping,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Series)
  async deleteSeries(
    @graphql.Args() args: DeleteSeriesArgs
  ): Promise<Series | null> {
    try {
      return await this.service.deleteSeries(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Genre], { name: "genre" })
  async findGenre(
    @graphql.Parent() parent: Series,
    @graphql.Args() args: GenreFindManyArgs
  ): Promise<Genre[]> {
    const results = await this.service.findGenre(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "director",
  })
  async getDirector(@graphql.Parent() parent: Series): Promise<User | null> {
    const result = await this.service.getDirector(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserSeriesMapping, {
    nullable: true,
    name: "userSeriesMapping",
  })
  async getUserSeriesMapping(
    @graphql.Parent() parent: Series
  ): Promise<UserSeriesMapping | null> {
    const result = await this.service.getUserSeriesMapping(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
